#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "whoogle"
name = "Whoogle"
description.en = "Self-hosted, ad-free, privacy-respecting metasearch engine"
description.fr = "Métamoteur de recherche auto-hébergé, sans publicité et respectueux de la vie privée"

version = "0.9.4~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "MIT"
code = "https://github.com/benbusby/whoogle-search"
fund ="https://ko-fi.com/benbusby"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "150M"
ram.runtime = "80M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://github.com/benbusby/whoogle-search/archive/refs/tags/v0.9.4.tar.gz"
        sha256 = "0f6847ff529a4e146c9967d0bb7c9cd1eeb55f43fdc2ec7570722046b591fc77"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "python3-dev, python3-venv, python3, python3-pip, libcurl4-openssl-dev, libssl-dev"
